workflows:
  android_debug:
    name: Android Debug APK
    environment:
      flutter: stable
    scripts:
      - flutter create . --platforms=android
      - flutter pub get
      - flutter build apk --release --split-per-abi   # ← BUNU KULLAN
    artifacts:
      - build/app/outputs/flutter-apk/*-release.apk   # ← Hepsini yayınla

