workflows:
  android_debug:
    name: Android Debug APK
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - flutter --version
      - flutter create . --platforms=android
      - flutter pub get
      - flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
