workflows:
  android_debug:
    name: Android Debug APK
    environment:
      flutter: stable
    scripts:
      - flutter create . --platforms=android
      - flutter pub get
      - flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
